version: '3.8'
services:
  fi-mcp-dev:
    build: .
    ports:
      - "8081:8080"
    environment:
      - FI_MCP_PORT=8080
    volumes:
      - ./static:/app/static
      - ./test_data_dir:/app/test_data_dir 